(use gauche.uvector)
(use gl)
(use gl.glfw)

(define (main args)
  (unless (glfw-init) 
    (display "failed to initialize GLFW" (current-error-port))
    (exit 1))
  (let ((window (glfw-create-window 700 700 "triangle" #f #f)))
    (unless window
      (display "failed to create GLFWwindow" (current-error-port))
      (exit 1))
    (glfw-window-hint GLFW_CONTEXT_VERSION_MAJOR 4)
    (glfw-window-hint GLFW_CONTEXT_VERSION_MAJOR 6)
    (glfw-make-context-current window)
    
    (gl-clear-color 0 0 0 1)
    (let loop () 
      (unless (glfw-window-should-close window)
        (glfw-swap-buffers window)
        (glfw-wait-events)
        (loop)))
    (glfw-destroy-window window)
    (glfw-terminate)
    (exit 0)))